name: 'Some computational genomics workflows'
repo: 'http://github.com/cumc/bioworkflows'
footer: "&copy 2020-current Gao Wang and others, Department of Neurology at Columbia University"
include_dir: ['variant-annotation', 'fine-mapping', 'variant-calling', 'multivariate-fine-mapping', 'GWAS', 'ldpred']
hide_navbar: ['variant-annotation', 'fine-mapping', 'variant-calling', 'multivariate-fine-mapping', 'GWAS', 'ldpred']
homepage: "Overview.ipynb"
# skip_homepage: False
# add_commit_info: True
# disqus: NULL
# release_message: NULL # type a release message to enable auto-commit, eg: "Build website via jnbinder"
# post_release_actions: NULL
# homepage_label: Overview # Set to NULL to disable
# source_label: "source" # Set to NULL to disable it; default is github octopus icon
# theme: "cosmo" # Theme from bootstrap
# font: "Droid Sans" # Set to NULL for theme default font
# notebook_toc: True
# long_autoindex: True # When set to `True` it uses the first paragraph under the title if available, instead of using the title, to make descriptions on the automatically generated for a page.
# reverse_autoindex: [] # Directories for which auto-index be reversed. This is useful when a folder has notebook named like `20160502_XX` because it will show the newer notebook on the top.
# report_style: False # Use SoS report style that hides codes by default for SoS notebooks
# remove_whiteline: False # When set to `True` the empty lines in the output HTML will be purged. This will make the code block read more compact.
# password_file: NULL # Load a list of folders / pages to be password protected, and their passwords. See example https://github.com/stephenslab/ipynb-website/blob/master/.passwd.
# site_url: NULL # Default uses github.io URL convention
# auto_highlight: NULL
