---
title: "New scrach"
author: "Mengyu Zhang"
date: "4/3/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
raw_beta = readRDS("./all_MVP_posteriors/raw_univariate_estimates/zmash_raw_univariate_MVP.rds")

raw_beta_se = bigreadr::fread2("./all_MVP_posteriors/raw_univariate_estimates/Merged_MVP_Full_se_raw.txt")

#chr_pos_allele2_lfsr = read.table("./all_MVP_posteriors/identifying_info/chr_pos_allele2_lfsr.txt")
```

```{r}
raw_beta_se = raw_beta_se %>% 
  data.frame() %>% 
  rename(marker = m.Marker)
raw_beta = raw_beta %>% 
  data.frame() %>% 
  mutate(marker = rownames(raw_beta))
```

```{r}
sumstats = inner_join(raw_beta_se,raw_beta, by = 'marker') %>% 
  select(marker, hdl,HDLSe,ldl,LDLSe, tg, TGSe, tc, TCSe)

head(sumstats)

colnames(sumstats) = c("marker", "hdl", "hdl_se", "ldl", "ldl_se", "tg", "tg_se", "tc", "tc_se")

sumstats = sumstats %>%
  extract(marker, into = c("chr", "pos"), regex = "([0-9]+)(\\:[0-9]+)") %>% 
  mutate(chr = as.numeric(chr),
         pos = as.numeric(str_replace(pos, ":","")))
```

```{r}
chr_pos = bigreadr::fread2("./all_MVP_posteriors/identifying_info/chr_pos_allele2_lfsr.txt")
head(chr_pos)
```

```{r}
chr_pos = chr_pos %>%
  extract(V1, into = c("chr", "pos"), regex = "([0-9]+)(\\:[0-9]+)") %>% 
  mutate(chr = as.numeric(chr),
         pos = as.numeric(str_replace(pos, ":",""))) %>% 
  rename(a0 = Allele1,
         a1 = Allele2,
         rsid = rsID) %>% 
  select(chr,pos,rsid,a0,a1)

```

```{r}
sumstats = inner_join(sumstats, chr_pos, by = c("chr","pos")) %>% select(chr, pos, rsid, a0, a1, everything())
```

```{r}
sumstats = sumstats %>% 
  mutate(hdl_z = hdl/hdl_se,
         hdl_p = 2*pnorm(-abs(hdl_z)),
         ldl_z = ldl/ldl_se,
         ldl_p = 2*pnorm(-abs(ldl_z)),
         tc_z = tc/tc_se,
         tc_p = 2*pnorm(-abs(tc_z)),
         tg_z = tg/tg_se,
         tg_p = 2*pnorm(-abs(tg_z))) %>% 
  select(-hdl_z,-ldl_z, -tc_z, -tg_z)

head(sumstats)
```


```{r}
sumstats_hdl  = sumstats %>% 
  select(chr, pos, rsid, a0,a1, hdl, hdl_se,hdl_p) %>% 
  rename(beta = hdl,
         beta_se = hdl_se,
         p = hdl_p)
head(sumstats_hdl)

sumstats_ldl  = sumstats %>% 
  select(chr, pos, rsid, a0, a1, ldl, ldl_se,ldl_p) %>% 
  rename(beta = ldl,
         beta_se = ldl_se,
         p = ldl_p)

sumstats_tc  = sumstats %>% 
  select(chr, pos, rsid, a0,a1, tc, tc_se,tc_p) %>% 
  rename(beta = tc,
         beta_se = tc_se,
         p = tc_p)

sumstats_tg  = sumstats %>% 
  select(chr, pos, rsid, a0,a1, tg, tg_se,tg_p) %>% 
  rename(beta = tg,
         beta_se = tg_se,
         p = tg_p)
```

```{r}
saveRDS(sumstats_hdl, file = "mvpdata/sumstats_hdl.rds")
saveRDS(sumstats_ldl, file = "mvpdata/sumstats_ldl.rds")
saveRDS(sumstats_tc, file = "mvpdata/sumstats_tc.rds")
saveRDS(sumstats_tg, file = "mvpdata/sumstats_tg.rds")
head(sumstats_tg)
```
# Poster

```{r}
pos_raw_beta = bigreadr::fread2("./all_MVP_posteriors/posterior_estimates/MVP_all_beta_posterior_beta.txt")

pos_raw_beta_se = bigreadr::fread2("./all_MVP_posteriors/posterior_estimates/posterior_beta_se.txt")

colnames(pos_raw_beta)=c("marker", "hdl","ldl","tg","tc")
colnames(pos_raw_beta_se)=c("marker", "hdl_se","ldl_se","tg_se","tc_se")
```

```{r}
head(pos_raw_beta)
```
```{r}
head(pos_raw_beta_se)
```


```{r}
pos_raw_beta_se = pos_raw_beta_se %>% 
  data.frame()
pos_raw_beta = pos_raw_beta %>% 
  data.frame()
```

```{r}
sumstats = inner_join(pos_raw_beta_se,pos_raw_beta, by = 'marker') %>% 
  select(marker, hdl,hdl_se,ldl,ldl_se, tg, tg_se, tc, tc_se)

head(sumstats)

colnames(sumstats) = c("marker", "hdl", "hdl_se", "ldl", "ldl_se", "tg", "tg_se", "tc", "tc_se")

sumstats = sumstats %>%
  extract(marker, into = c("chr", "pos"), regex = "([0-9]+)(\\:[0-9]+)") %>% 
  mutate(chr = as.numeric(chr),
         pos = as.numeric(str_replace(pos, ":","")))
```

```{r}
chr_pos = bigreadr::fread2("./all_MVP_posteriors/identifying_info/chr_pos_allele2_lfsr.txt")
head(chr_pos)
```

